name: Run test
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウトする
      - uses: actions/checkout@v3

      # Nodeをセットアップする
      - uses: actions/setup-node@v2

      # testを実行する
      - run: npm run test
